"""Add price and other fields to tier table

Revision ID: 5afd5ee0ede0
Revises: 613f99e26a88
Create Date: 2025-10-14 11:14:26.564879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5afd5ee0ede0'
down_revision: Union[str, None] = '613f99e26a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.add_column('tier', sa.Column('price', sa.String(length=50), nullable=False))
    op.add_column('tier', sa.Column('duration', sa.String(length=100), nullable=True))
    op.add_column('tier', sa.Column('description', sa.String(length=255), nullable=False))
    op.add_column('tier', sa.Column('sub_description', sa.String(length=255), nullable=True))
    op.add_column('tier', sa.Column('features', sa.JSON(), nullable=False))
    op.add_column('tier', sa.Column('button_text', sa.String(length=100), nullable=False))
    op.add_column('tier', sa.Column('badge', sa.String(length=50), nullable=True))
    op.add_column('tier', sa.Column('button_variant', sa.String(length=20), nullable=False))
    op.add_column('tier', sa.Column('highlighted', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('tier_id_key'), 'tier', type_='unique')
    op.drop_constraint(op.f('tier_name_key'), 'tier', type_='unique')
    op.create_index(op.f('ix_tier_name'), 'tier', ['name'], unique=True)
    op.drop_column('tier', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tier', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tier_name'), table_name='tier')
    op.create_unique_constraint(op.f('tier_name_key'), 'tier', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('tier_id_key'), 'tier', ['id'], postgresql_nulls_not_distinct=False)
    op.drop_column('tier', 'highlighted')
    op.drop_column('tier', 'button_variant')
    op.drop_column('tier', 'badge')
    op.drop_column('tier', 'button_text')
    op.drop_column('tier', 'features')
    op.drop_column('tier', 'sub_description')
    op.drop_column('tier', 'description')
    op.drop_column('tier', 'duration')
    op.drop_column('tier', 'price')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
