"""Add role column to user table

Revision ID: 613f99e26a88
Revises: 15f8d3fb3fe0
Create Date: 2025-10-10 16:08:25.245902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '613f99e26a88'
down_revision: Union[str, None] = '15f8d3fb3fe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop old table if needed (auto-generated)
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')

    # ✅ Add 'role' with a default value so existing rows get 'user'
    op.add_column(
        'user',
        sa.Column('role', sa.String(length=10), server_default='user', nullable=False)
    )

    # Remove 'terms_accepted' column if it’s no longer needed
    op.drop_column('user', 'terms_accepted')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('terms_accepted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'role')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
