"""Add role column to user table

Revision ID: 613f99e26a88
Revises: 15f8d3fb3fe0
Create Date: 2025-10-10 16:08:25.245902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '613f99e26a88'
down_revision: Union[str, None] = '15f8d3fb3fe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add 'role' column with a default value so existing rows get 'user'
    op.add_column(
        'user',
        sa.Column('role', sa.String(length=10), server_default='user', nullable=False)
    )

    # Remove 'terms_accepted' column
    op.drop_column('user', 'terms_accepted')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('terms_accepted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
