"""Add campaigns_created fields to User

Revision ID: b221c8e6836b
Revises: befef5e629ce
Create Date: 2025-10-16 10:10:41.674542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b221c8e6836b'
down_revision: Union[str, None] = 'befef5e629ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('campaigns_used', sa.Integer(), nullable=False),
    sa.Column('campaigns_created_this_month', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tier_id'], ['tier.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscription_tier_id'), 'user_subscription', ['tier_id'], unique=False)
    op.create_index(op.f('ix_user_subscription_user_id'), 'user_subscription', ['user_id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('orig_link', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rank_in_feed', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('title_key', sa.String(length=500), nullable=True),
    sa.Column('row_id', sa.String(length=100), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('position_w', sa.Float(), nullable=False),
    sa.Column('est_ars', sa.Float(), nullable=False),
    sa.Column('pickup_count', sa.Integer(), nullable=False),
    sa.Column('inferred_clicks', sa.Float(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('is_aggregator', sa.Boolean(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_campaign_id'), 'articles', ['campaign_id'], unique=False)
    op.create_table('brand_kpis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('mentions', sa.Integer(), nullable=False),
    sa.Column('weighted_reach', sa.Float(), nullable=False),
    sa.Column('avg_sentiment', sa.Float(), nullable=False),
    sa.Column('avg_engagement_rate', sa.Float(), nullable=False),
    sa.Column('avg_pickup_rate', sa.Float(), nullable=False),
    sa.Column('inferred_clicks', sa.Float(), nullable=False),
    sa.Column('share_of_voice', sa.Float(), nullable=False),
    sa.Column('ad_equivalent_value_inr', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_kpis_campaign_id'), 'brand_kpis', ['campaign_id'], unique=False)
    op.create_table('campaign_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_jobs_campaign_id'), 'campaign_jobs', ['campaign_id'], unique=True)
    op.create_table('generic_keyword_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('generic_keyword_mentions', sa.Integer(), nullable=False),
    sa.Column('positive_generic_mentions', sa.Integer(), nullable=False),
    sa.Column('positive_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generic_keyword_analyses_campaign_id'), 'generic_keyword_analyses', ['campaign_id'], unique=False)
    op.create_table('publication_kpis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('mentions', sa.Integer(), nullable=False),
    sa.Column('weighted_reach', sa.Float(), nullable=False),
    sa.Column('avg_engagement_rate', sa.Float(), nullable=False),
    sa.Column('avg_sentiment', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('is_aggregator', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_kpis_campaign_id'), 'publication_kpis', ['campaign_id'], unique=False)
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.add_column('campaigns', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('campaigns', sa.Column('brand_keyword', sa.Text(), nullable=False))
    op.add_column('campaigns', sa.Column('current_step', sa.Integer(), nullable=False))
    op.add_column('campaigns', sa.Column('form_data', sa.JSON(), nullable=False))
    op.add_column('campaigns', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('campaigns', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('campaigns', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('campaigns', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('campaigns', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('campaigns', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('campaigns', 'competitors',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('campaigns', 'regions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('campaigns', 'status',
               existing_type=postgresql.ENUM('pending', 'active', 'paused', 'completed', 'stopped', 'error', name='campaignstatus'),
               type_=sa.String(length=20),
               nullable=False)
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.create_index(op.f('ix_campaigns_user_id'), 'campaigns', ['user_id'], unique=False)
    op.drop_constraint(op.f('campaigns_user_id_fkey'), 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'user', ['user_id'], ['id'])
    op.drop_column('campaigns', 'brand_keywords')
    op.drop_column('campaigns', 'excel_report_path')
    op.drop_column('campaigns', 'html_report_path')
    op.drop_column('campaigns', 'is_deleted')
    op.drop_column('campaigns', 'last_updated')
    op.drop_column('campaigns', 'title')
    op.drop_column('campaigns', 'progress')
    op.add_column('tier', sa.Column('max_campaigns', sa.Integer(), nullable=False))
    op.add_column('tier', sa.Column('max_competitors', sa.Integer(), nullable=False))
    op.add_column('tier', sa.Column('max_duration_days', sa.Integer(), nullable=False))
    op.add_column('tier', sa.Column('max_articles_per_campaign', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('campaigns_created', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('campaigns_created_this_month', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'campaigns_created_this_month')
    op.drop_column('user', 'campaigns_created')
    op.drop_column('tier', 'max_articles_per_campaign')
    op.drop_column('tier', 'max_duration_days')
    op.drop_column('tier', 'max_competitors')
    op.drop_column('tier', 'max_campaigns')
    op.add_column('campaigns', sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('campaigns', sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('html_report_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('excel_report_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('brand_keywords', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key(op.f('campaigns_user_id_fkey'), 'campaigns', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_campaigns_user_id'), table_name='campaigns')
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.alter_column('campaigns', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('pending', 'active', 'paused', 'completed', 'stopped', 'error', name='campaignstatus'),
               nullable=True)
    op.alter_column('campaigns', 'regions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('campaigns', 'competitors',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('campaigns', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('campaigns', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('campaigns', 'completed_at')
    op.drop_column('campaigns', 'updated_at')
    op.drop_column('campaigns', 'created_at')
    op.drop_column('campaigns', 'error_message')
    op.drop_column('campaigns', 'form_data')
    op.drop_column('campaigns', 'current_step')
    op.drop_column('campaigns', 'brand_keyword')
    op.drop_column('campaigns', 'name')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    op.drop_index(op.f('ix_publication_kpis_campaign_id'), table_name='publication_kpis')
    op.drop_table('publication_kpis')
    op.drop_index(op.f('ix_generic_keyword_analyses_campaign_id'), table_name='generic_keyword_analyses')
    op.drop_table('generic_keyword_analyses')
    op.drop_index(op.f('ix_campaign_jobs_campaign_id'), table_name='campaign_jobs')
    op.drop_table('campaign_jobs')
    op.drop_index(op.f('ix_brand_kpis_campaign_id'), table_name='brand_kpis')
    op.drop_table('brand_kpis')
    op.drop_index(op.f('ix_articles_campaign_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_user_subscription_user_id'), table_name='user_subscription')
    op.drop_index(op.f('ix_user_subscription_tier_id'), table_name='user_subscription')
    op.drop_table('user_subscription')
    # ### end Alembic commands ###
