"""fix campaign_id type

Revision ID: ee2b4bb900e8
Revises: b221c8e6836b
Create Date: 2025-10-17 10:55:22.229412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee2b4bb900e8'
down_revision: Union[str, None] = 'b221c8e6836b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'post', ['id'])
    # Description column doesn't exist in base schema, so skip dropping it
    # op.drop_column('post', 'description')
    op.create_unique_constraint(None, 'rate_limit', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rate_limit', type_='unique')
    op.add_column('post', sa.Column('description', sa.VARCHAR(length=63206), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'post', type_='unique')
    # ### end Alembic commands ###
